apiVersion: v1
kind: Service
metadata:
  labels:
    app: upload
  name: upload
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: upload
  sessionAffinity: None
  type: ClusterIP
